name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14.2
      id: go
    
    - name: Set up binutils-mingw
      run: sudo apt-get install binutils-mingw-w64-x86-64
      
    - name: Set up GCC-mingw
      run: sudo apt-get install gcc-mingw-w64-x86-64

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    
    - name: Build
      run: make GOARCH=amd64 GOOS=windows CC=x86_64-w64-mingw32-gcc-8 CGO_ENABLED=1
      working-directory: ./stammel
      
    - uses: actions/upload-artifact@v2
      with:
        name:  my-artifact
        path:  ./bin

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag	: latest 
          prerelease: false
          files: |
            ./bin/stammel_go.dll
